# Pango events within the ARG

In this notebook we examine how well the ARG reflects evolutionary events implicit in the pango naming system.


## Summary (v2.2 ARG)

Of the 3032 distinct pango lineages in the ARG, 2037 of these (comprising 898542 samples) match perfectly, with unique origination events in the ARG where all samples assigned a given lineage descend from the first node assigned that lineage. A further 420 lineages (730289 samples) match perfectly when we count the descendants of the  parent of the first node (accounting for polytomies in which multiple originating nodes for a given lineage are siblings). We then have 541 lineages (522442 samples) where the difference in the number of descendants of the first node's parent is < 100. The remaining 34 lineages (963336 samples) are dominated by a few large lineages such as AY.4 (552697 samples) BA.1.1 (177608 samples)  which have multiple non-sibling origins within the ARG.

In [1]:
import sc2ts
import tszip
import pathlib
import numpy as np
import pandas as pd
import concurrent.futures as cf
from tqdm.notebook import tqdm

datadir = pathlib.Path("../data")

## Code

In [2]:
ts = tszip.load(datadir / "sc2ts_viridian_v2.2.trees.tsz")

In [3]:
df_node = sc2ts.node_data(ts, inheritance_stats=True).set_index("node_id")
df_node["node_time"] = ts.nodes_time
df_node

,pango,sample_id,scorpio,is_sample,is_recombinant,num_mutations,max_descendant_samples,date,node_time
node_id,,,,,,,,,
0,B,Vestigial_ignore,.,False,False,0,0,2019-11-18,1662.080921
1,B,Wuhan/Hu-1/2019,.,False,False,0,3114609,2019-12-26,1624.000000
2,A,SRR11772659,.,True,False,1,320,2020-01-19,1600.000000
3,B,SRR11397727,.,True,False,0,1,2020-01-24,1595.000000
4,B,SRR11397730,.,True,False,0,1,2020-01-24,1595.000000
...,...,...,...,...,...,...,...,...,...
3409257,AY.44,,Delta (B.1.617.2-like),False,False,2,50,2021-04-11,1152.000000
3409258,AY.30,,Delta (B.1.617.2-like),False,False,3,14,2020-12-14,1270.344428
3409259,B.1.427,,Epsilon (B.1.427-like),False,False,5,7,2021-02-03,1219.818601
3409260,AY.75,,Delta (B.1.617.2-like),False,False,9,29,2021-05-11,1122.808174
3409261,XBB.1.5,,Omicron (XBB-like),False,False,1,5,2023-01-02,521.000000

## Concordance with original assignments by Viridian

We extract the original Pango lineage assignments (version 1.29 and version 1.21) from the dataset and join this with our nodes samples to measure the levels of concordance between the three different calls for the same sequences.

In [4]:
ds = sc2ts.Dataset(datadir / "viridian_mafft_2024-10-14_v1.vcz.zip")
ds

Dataset at ../data/viridian_mafft_2024-10-14_v1.vcz.zip with 4484157 samples, 29903 variants, and 30 metadata fields. See ds.metadata.field_descriptors() for a description of the fields.

In [5]:
df_sample = df_node[df_node.is_sample].set_index("sample_id")
df_sample

,pango,scorpio,is_sample,is_recombinant,num_mutations,max_descendant_samples,date,node_time
sample_id,,,,,,,,
SRR11772659,A,.,True,False,1,320,2020-01-19,1600.0
SRR11397727,B,.,True,False,0,1,2020-01-24,1595.0
SRR11397730,B,.,True,False,0,1,2020-01-24,1595.0
SRR11597198,A,.,True,False,0,1,2020-01-25,1594.0
SRR11597221,A,.,True,False,0,1,2020-01-25,1594.0
...,...,...,...,...,...,...,...,...
SRR29413084,KP.2.15,Omicron (BA.2-like),True,False,0,1,2024-06-02,4.0
SRR29412872,KP.3.3,Omicron (BA.2-like),True,False,0,1,2024-06-04,2.0
SRR29413186,KP.3.1.1,Omicron (BA.2-like),True,False,0,1,2024-06-04,2.0
SRR29413045,KP.2,Omicron (BA.2-like),True,False,0,1,2024-06-05,1.0
SRR29413176,JN.1.16.1,Omicron (BA.2-like),True,False,0,1,2024-06-05,1.0

In [6]:
df_sample = df_sample.join(ds.metadata.as_dataframe(["Viridian_pangolin", "Viridian_pangolin_1.29", "Viridian_scorpio_1.29"]))

In [7]:
df_sample = df_sample.rename(columns={"Viridian_pangolin": "Viridian_pangolin_1.21"})
df_sample

,pango,scorpio,is_sample,is_recombinant,num_mutations,max_descendant_samples,date,node_time,Viridian_pangolin_1.21,Viridian_pangolin_1.29,Viridian_scorpio_1.29
sample_id,,,,,,,,,,,
SRR11772659,A,.,True,False,1,320,2020-01-19,1600.0,A,A,.
SRR11397727,B,.,True,False,0,1,2020-01-24,1595.0,B,B,.
SRR11397730,B,.,True,False,0,1,2020-01-24,1595.0,B,B,.
SRR11597198,A,.,True,False,0,1,2020-01-25,1594.0,A,A,.
SRR11597221,A,.,True,False,0,1,2020-01-25,1594.0,A,A,.
...,...,...,...,...,...,...,...,...,...,...,...
SRR29413084,KP.2.15,Omicron (BA.2-like),True,False,0,1,2024-06-02,4.0,BA.2,KP.2.15,Omicron (BA.2-like)
SRR29412872,KP.3.3,Omicron (BA.2-like),True,False,0,1,2024-06-04,2.0,BA.2,KP.3.3,Omicron (BA.2-like)
SRR29413186,KP.3.1.1,Omicron (BA.2-like),True,False,0,1,2024-06-04,2.0,BA.2,KP.3.1.1,Omicron (BA.2-like)
SRR29413045,KP.2,Omicron (BA.2-like),True,False,0,1,2024-06-05,1.0,BA.2,KP.2,Omicron (BA.2-like)
SRR29413176,JN.1.16.1,Omicron (BA.2-like),True,False,0,1,2024-06-05,1.0,BA.2,JN.1.16.1,Omicron (BA.2-like)

In [8]:
np.sum(df_sample["Viridian_pangolin_1.21"] != df_sample["Viridian_pangolin_1.29"])

np.int64(74410)

In [9]:
print(f"{_ / df_sample.shape[0] * 100: .2f}")

 2.39

In [10]:
np.sum(df_sample["pango"] != df_sample["Viridian_pangolin_1.29"])

np.int64(28817)

In [11]:
print(f"{_ / df_sample.shape[0] * 100: .2f}")

 0.93

11004 samples differ in their Scorpio designations.

In [12]:
df_sample[df_sample["scorpio"] != df_sample["Viridian_scorpio_1.29"]][["scorpio", "Viridian_scorpio_1.29"]]

                         scorpio         Viridian_scorpio_1.29
sample_id
SRR27324949                    .           Beta (B.1.351-like)
SRR27237896                    .           Beta (B.1.351-like)
SRR13620105                    .           Beta (B.1.351-like)
SRR13620108                    .           Beta (B.1.351-like)
SRR13620095                    .           Beta (B.1.351-like)
...                          ...                           ...
ERR13322696  Omicron (BA.2-like)  Probable Omicron (BA.2-like)
SRR29261519  Omicron (BA.2-like)          Omicron (Unassigned)
SRR28516178   Omicron (XBB-like)          Omicron (XBB.1-like)
SRR28814206   Omicron (XBB-like)          Omicron (XBB.1-like)
SRR28965579  Omicron (BA.2-like)          Omicron (Unassigned)

[11004 rows x 2 columns]

## Origination events

How well does the ARG reflect the phylogenetic structure of the pango naming system?

We sort the nodes by the descending samples first, and then by node time. This should guarantee that the first node in the dataframe for each pango lineage is the "majority" node for that pango.

In [13]:
dfn_sorted = df_node.sort_values(["max_descendant_samples", "node_time"], ascending=False)
dfn_sorted

,pango,sample_id,scorpio,is_sample,is_recombinant,num_mutations,max_descendant_samples,date,node_time
node_id,,,,,,,,,
1,B,Wuhan/Hu-1/2019,.,False,False,0,3114609,2019-12-26,1624.000000
33,B,,.,False,False,1,3109263,2019-12-26,1624.000000
12,B.1,SRR11597205,.,True,False,2,3109259,2020-01-28,1591.661216
68,B.1,,.,False,False,1,3109244,2020-01-28,1591.661216
118,B.1.1,,.,False,False,3,1651314,2020-01-28,1591.010638
...,...,...,...,...,...,...,...,...,...
1893383,JN.1.4.5,SRR29413085,Omicron (BA.2-like),True,False,6,1,2024-06-06,0.000000
1893384,LB.1.7,SRR29413113,Omicron (BA.2-like),True,False,2,1,2024-06-06,0.000000
1893385,KP.1.1.3,SRR29413120,Omicron (BA.2-like),True,False,7,1,2024-06-06,0.000000
1893386,LN.1.1,SRR29413167,Omicron (BA.2-like),True,False,1,1,2024-06-06,0.000000
0,B,Vestigial_ignore,.,False,False,0,0,2019-11-18,1662.080921

In [14]:
dfn_pango = dfn_sorted.reset_index().groupby(["pango"]).first()
dfn_pango

,node_id,sample_id,scorpio,is_sample,is_recombinant,num_mutations,max_descendant_samples,date,node_time
pango,,,,,,,,,
A,9,,.,False,False,1,1318,2019-12-26,1624.000000
A.1,273,,.,False,False,2,283,2020-01-19,1600.000000
A.11,4097,SRR23586010,.,True,False,3,1,2020-03-28,1531.000000
A.2,639,,.,False,False,4,242,2020-02-01,1587.000000
A.2.2,1269,ERR12537611,.,True,False,1,81,2020-03-19,1540.000000
...,...,...,...,...,...,...,...,...,...
XW,1375030,,Omicron (BA.2-like),False,True,1,40,2022-03-03,826.642422
XY,1413955,,Omicron (Unassigned),False,True,2,23,2022-03-15,814.000000
XZ,1380286,,Omicron (BA.2-like),False,False,1,51,2022-03-09,820.000000
Y.1,60919,,.,False,False,1,38,2020-08-18,1388.000000
Z.1,34064,ERR4664951,.,True,False,3,217,2020-09-15,1360.000000

In [15]:

def worker(work):
    pango, row = work
    df_pango = df_node[df_node.pango == pango]
    samples = df_pango[df_pango.is_sample].index
    root = row["node_id"]
    tracked_samples = []
    parent_tracked_samples = []
    for tree in ts.trees(tracked_samples=samples):
        tracked_samples.append(tree.num_tracked_samples(root))
        parent = tree.parent(root)
        if parent != -1:
            parent_tracked_samples.append(tree.num_tracked_samples(parent))
        else:
            parent_tracked_samples.append(0)
            
    return {
        "pango": pango,
        "root": root,
        "total_samples": len(samples),
        "max_descendants": np.max(tracked_samples),
        "min_descendants": np.min(tracked_samples),
        "parent_max_descendants": np.max(parent_tracked_samples),
        "parent_min_descendants": np.min(parent_tracked_samples),
    }
    
# Note: set things up this way with an eye to using concurrent.futures,
# but it was totally GIL-blocked, seemingly. Not worth setting up
# process level parallelism.
data = []
for work in tqdm(dfn_pango.iterrows(), total=dfn_pango.shape[0]):
    result = worker(work)
    data.append(result)
        
df_pango_events = pd.DataFrame(data)
df_pango_events

  0%|          | 0/3032 [00:00<?, ?it/s]

,pango,root,total_samples,max_descendants,min_descendants,parent_max_descendants,parent_min_descendants
0,A,9,317,317,317,317,317
1,A.1,273,283,283,283,283,283
2,A.11,4097,1,1,1,1,1
3,A.2,639,56,56,56,56,56
4,A.2.2,1269,81,81,81,81,81
...,...,...,...,...,...,...,...
3027,XW,1375030,37,37,37,37,37
3028,XY,1413955,23,23,23,23,23
3029,XZ,1380286,51,51,51,51,51
3030,Y.1,60919,38,38,38,38,38
3031,Z.1,34064,217,217,217,217,217

In [16]:
total = df_pango_events["total_samples"]
diff = (total - df_pango_events["max_descendants"]).abs() 
diff_parent = (total - df_pango_events["parent_max_descendants"]).abs() 
df_pango_events["diff"] = diff
df_pango_events["diff_parent"] = diff_parent
df_pango_events["relative_diff"] = diff / total
df_pango_events["relative_diff_parent"] = diff_parent / total

In [17]:
df_pango_events

,pango,root,total_samples,max_descendants,min_descendants,parent_max_descendants,parent_min_descendants,diff,diff_parent,relative_diff,relative_diff_parent
0,A,9,317,317,317,317,317,0,0,0.0,0.0
1,A.1,273,283,283,283,283,283,0,0,0.0,0.0
2,A.11,4097,1,1,1,1,1,0,0,0.0,0.0
3,A.2,639,56,56,56,56,56,0,0,0.0,0.0
4,A.2.2,1269,81,81,81,81,81,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3027,XW,1375030,37,37,37,37,37,0,0,0.0,0.0
3028,XY,1413955,23,23,23,23,23,0,0,0.0,0.0
3029,XZ,1380286,51,51,51,51,51,0,0,0.0,0.0
3030,Y.1,60919,38,38,38,38,38,0,0,0.0,0.0
3031,Z.1,34064,217,217,217,217,217,0,0,0.0,0.0

In [18]:
perfect = df_pango_events[df_pango_events["diff"] == 0]
perfect

,pango,root,total_samples,max_descendants,min_descendants,parent_max_descendants,parent_min_descendants,diff,diff_parent,relative_diff,relative_diff_parent
0,A,9,317,317,317,317,317,0,0,0.0,0.0
1,A.1,273,283,283,283,283,283,0,0,0.0,0.0
2,A.11,4097,1,1,1,1,1,0,0,0.0,0.0
3,A.2,639,56,56,56,56,56,0,0,0.0,0.0
4,A.2.2,1269,81,81,81,81,81,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3027,XW,1375030,37,37,37,37,37,0,0,0.0,0.0
3028,XY,1413955,23,23,23,23,23,0,0,0.0,0.0
3029,XZ,1380286,51,51,51,51,51,0,0,0.0,0.0
3030,Y.1,60919,38,38,38,38,38,0,0,0.0,0.0
3031,Z.1,34064,217,217,217,217,217,0,0,0.0,0.0

In [19]:
perfect.shape

(2037, 11)

In [20]:
perfect.total_samples.sum()

np.int64(898542)

# Consider the effects of polytomies

In [21]:
perfect_for_parent = df_pango_events[(df_pango_events["diff"] > 0) & (df_pango_events["diff_parent"] == 0)]
perfect_for_parent

,pango,root,total_samples,max_descendants,min_descendants,parent_max_descendants,parent_min_descendants,diff,diff_parent,relative_diff,relative_diff_parent
14,A.5,934,57,56,56,57,57,1,0,0.017544,0.0
37,AY.1,261820,476,468,468,476,476,8,0,0.016807,0.0
42,AY.103,230025,74949,74910,74903,74949,74944,39,0,0.000520,0.0
45,AY.105,288761,242,175,173,242,242,67,0,0.276860,0.0
58,AY.116,331324,176,96,95,176,176,80,0,0.454545,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2921,XBB.2.4,1757279,29,28,28,29,29,1,0,0.034483,0.0
2927,XBB.2.7,1748415,9,3,3,9,9,6,0,0.666667,0.0
2949,XBF.2,1756568,7,4,4,7,7,3,0,0.428571,0.0
2952,XBF.5,1770529,8,7,7,8,8,1,0,0.125000,0.0
3019,XM,1178986,33,31,31,33,31,2,0,0.060606,0.0

In [22]:
perfect_for_parent.shape

(420, 11)

In [23]:
perfect_for_parent.total_samples.sum()

np.int64(730289)

# The rest

In [24]:
not_perfect = df_pango_events[(df_pango_events["diff"] > 0) & (df_pango_events["diff_parent"] != 0)]
not_perfect

,pango,root,total_samples,max_descendants,min_descendants,parent_max_descendants,parent_min_descendants,diff,diff_parent,relative_diff,relative_diff_parent
39,AY.100,308428,21263,20177,19874,20177,19874,1086,1086,0.051075,0.051075
46,AY.106,287068,171,168,168,170,170,3,1,0.017544,0.005848
47,AY.107,257797,839,633,630,633,630,206,206,0.245530,0.245530
49,AY.109,391071,486,476,475,476,475,10,10,0.020576,0.020576
51,AY.110,327913,802,746,746,746,746,56,56,0.069825,0.069825
...,...,...,...,...,...,...,...,...,...,...,...
3004,XDK.5,1892678,9,6,6,6,6,3,3,0.333333,0.333333
3005,XDP,1868714,80,62,62,62,62,18,18,0.225000,0.225000
3006,XDP.1,1880135,32,24,24,24,24,8,8,0.250000,0.250000
3008,XDP.3,1871824,15,13,13,13,13,2,2,0.133333,0.133333
3013,XEB,1873501,9,5,5,5,5,4,4,0.444444,0.444444

In [25]:
not_perfect.total_samples.sum()

np.int64(1485778)

## Lineages that are pretty close 

And have a reasonable number of samples

In [26]:
close_to_right = not_perfect[(not_perfect["diff_parent"] < 100)]
close_to_right

,pango,root,total_samples,max_descendants,min_descendants,parent_max_descendants,parent_min_descendants,diff,diff_parent,relative_diff,relative_diff_parent
46,AY.106,287068,171,168,168,170,170,3,1,0.017544,0.005848
49,AY.109,391071,486,476,475,476,475,10,10,0.020576,0.020576
51,AY.110,327913,802,746,746,746,746,56,56,0.069825,0.069825
52,AY.111,252255,5206,5161,5161,5201,5201,45,5,0.008644,0.000960
53,AY.112,257423,490,469,469,482,481,21,8,0.042857,0.016327
...,...,...,...,...,...,...,...,...,...,...,...
3004,XDK.5,1892678,9,6,6,6,6,3,3,0.333333,0.333333
3005,XDP,1868714,80,62,62,62,62,18,18,0.225000,0.225000
3006,XDP.1,1880135,32,24,24,24,24,8,8,0.250000,0.250000
3008,XDP.3,1871824,15,13,13,13,13,2,2,0.133333,0.133333
3013,XEB,1873501,9,5,5,5,5,4,4,0.444444,0.444444

In [27]:
close_to_right.shape

(541, 11)

In [28]:
close_to_right.total_samples.sum()

np.int64(522442)

## Important stuff that's a long way off

In [29]:
important = not_perfect[not_perfect["diff_parent"] >= 100]
important.sort_values("total_samples", ascending=False)

,pango,root,total_samples,max_descendants,min_descendants,parent_max_descendants,parent_min_descendants,diff,diff_parent,relative_diff,relative_diff_parent
136,AY.4,175379,552697,550067,549804,551920,551663,2630,777,0.004758,0.001406
985,BA.1.1,903395,177608,157125,156998,177067,177059,20483,541,0.115327,0.003046
1019,BA.1.17.2,937732,49488,43633,43626,45377,45370,5855,4111,0.118312,0.083071
1160,BA.2.9,990865,37867,34841,34836,37634,37630,3026,233,0.079911,0.006153
1011,BA.1.15,926284,27920,24667,24661,24674,24668,3253,3246,0.116511,0.116261
39,AY.100,308428,21263,20177,19874,20177,19874,1086,1086,0.051075,0.051075
995,BA.1.1.18,998290,19362,9511,9496,10201,10184,9851,9161,0.508780,0.473143
1020,BA.1.18,961188,13307,8862,8846,8887,8871,4445,4420,0.334035,0.332156
131,AY.39,273858,12971,12097,11951,12097,11951,874,874,0.067381,0.067381
62,AY.119,271975,10025,9704,9668,9709,9673,321,316,0.032020,0.031521
1034,BA.2.1,1092502,7103,6460,6460,6462,6462,643,641,0.090525,0.090244
82,AY.126,326374,6241,5429,5428,5429,5428,812,812,0.130107,0.130107
1022,BA.1.20,971017,6114,5603,5601,5606,5604,511,508,0.083579,0.083088
61,AY.118,321009,4815,2639,2614,2689,2664,2176,2126,0.451921,0.441537
63,AY.119.2,334127,4009,3802,3769,3803,3770,207,206,0.051634,0.051384
132,AY.39.1,319149,2027,1788,1783,1788,1783,239,239,0.117908,0.117908
2696,XBB.1,1675918,1383,1050,1044,1116,1110,333,267,0.240781,0.193059
1526,BQ.1.1.4,1659262,1094,894,894,920,920,200,174,0.182815,0.159049
2405,JN.1.4.5,1858216,1030,727,725,777,775,303,253,0.294175,0.245631
47,AY.107,257797,839,633,630,633,630,206,206,0.245530,0.245530
996,BA.1.1.2,1016716,823,576,576,638,637,247,185,0.300122,0.224787
1092,BA.2.38,1272257,809,607,607,607,607,202,202,0.249691,0.249691
157,AY.4.9,317042,624,374,374,438,438,250,186,0.400641,0.298077
2468,JN.1.8.1,1855239,586,447,447,447,447,139,139,0.237201,0.237201
2460,JN.1.7,1856865,570,459,459,459,459,111,111,0.194737,0.194737
1172,BA.4.1.1,1497352,529,100,100,100,100,429,429,0.810964,0.810964
2396,JN.1.39,1855163,452,346,345,346,345,106,106,0.234513,0.234513
1002,BA.1.1.8,935849,393,243,243,243,243,150,150,0.381679,0.381679
1510,BQ.1.1.24,1705795,366,186,186,186,186,180,180,0.491803,0.491803
2411,JN.1.42,1859367,263,115,115,115,115,148,148,0.562738,0.562738
2832,XBB.1.5.47,1736352,232,107,107,107,107,125,125,0.538793,0.538793
1111,BA.2.52,1399337,202,99,99,99,99,103,103,0.509901,0.509901
2658,Q.1,208579,181,73,73,73,73,108,108,0.596685,0.596685
2860,XBB.1.5.73,1820044,143,18,18,18,18,125,125,0.874126,0.874126

In [30]:
important.shape

(34, 11)

In [31]:
important.total_samples.sum()

np.int64(963336)

In [32]:
df_pango_events.to_csv(datadir / "pango_events_in_arg.csv", index=False)