In [ ]:
from pathlib import Path
import numpy as np
import pandas as pd

In [3]:
recomb_file = Path("../data/recombinants.csv")
recomb_df = pd.read_csv(recomb_file)
recomb_df

,recombinant,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,...,parent_mrca_pango,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts
0,1438470,SRR19695004,1,1,1,519,670,2,COVID-AMPLISEQ-V1,.,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,True,3,2,55,False,6
1,1540083,ERR9939974,1,1,1,695,958,1,COVID-ARTIC-V4.1,.,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,4,1,12,False,9
2,752955,SRR20259474,1,1,1,510,1222,1,COVID-AMPLISEQ-V1,.,...,B.1.617.2,Delta (B.1.617.2-like),1268.244029,2020-12-16,False,2,2,19,False,5
3,1639578,ERR10219711,2,1,1,695,1453,2,COVID-ARTIC-V4.1,.,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,3,0,12,False,6
4,1798212,ERR11184433,1,1,1,695,1545,2,COVID-ARTIC-V4.1,.,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,12,1,43,False,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,1556595,ERR12781803,6,1,1,29509,29739,1,COVID-ARTIC-V3,.,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,6,24,2,False,6
1315,1750096,ERR13040343,1,1,1,29509,29739,1,COVID-ARTIC-V3,.,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,11,35,2,False,6
1316,1756387,ERR13041473,2,1,1,29509,29739,2,COVID-ARTIC-V3,.,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,13,36,2,False,7
1317,1179983,SRR25727637,1,1,1,29422,29751,1,COVID-MIDNIGHT-1200,.,...,B.1,.,1591.661216,2020-01-28,False,4,62,1,False,5
1318,1771516,ERR11006399,1,1,1,28704,29754,3,COVID-ARTIC-V4.1,.,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,True,11,48,1,False,7

In [ ]:
# Good recombinants
pd.set_option("display.max_rows", 1000)
recomb_df[recomb_df['net_min_supporting_loci_lft_rgt_ge_4']][
    [
        'recombinant',
        'net_min_supporting_loci_lft_rgt_ge_4',
        'net_min_supporting_loci_lft',
        'net_min_supporting_loci_rgt',
        'num_mns_left',
        'mns_left',
        'num_mns_right',
        'mns_right',
    ]
].sort_values(
    by=[
        'num_mns_right',
        'num_mns_left',
    ],
    ascending=False
).head(116)

,recombinant,net_min_supporting_loci_lft_rgt_ge_4,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,num_mns_left,mns_left,num_mns_right,mns_right
53,425792,True,8,61,0,,2,"MNM1,MNM1a"
134,1446971,True,15,34,0,,2,"MNM2,MNM3"
23,1352577,True,5,47,0,,1,MNM3
24,1169203,True,5,44,0,,1,MNM3
25,1578059,True,5,43,0,,1,MNM3
26,1375030,True,4,44,0,,1,MNM3
27,1818894,True,4,43,0,,1,MNM3
29,1702293,True,5,39,0,,1,MNM3
33,1412237,True,6,46,0,,1,MNM3
34,1251095,True,7,44,0,,1,MNM3
39,1358902,True,8,46,0,,1,MNM3
48,1764888,True,4,38,0,,1,MNM3
50,1247289,True,8,81,0,,1,mnS3
54,1242085,True,8,78,0,,1,mnS3
55,1105581,True,7,73,0,,1,mnS3
64,90053,True,6,38,0,,1,mnS3
67,1685198,True,6,26,0,,1,MNM3
74,1706445,True,9,36,0,,1,MNM3
77,1350909,True,7,47,0,,1,MNM3
79,1218637,True,10,40,0,,1,MNM3
92,1251239,True,10,40,0,,1,MNM3
95,1093814,True,8,41,0,,1,MNM3
102,1705711,True,8,29,0,,1,MNM3
103,1782627,True,5,42,0,,1,MNM3
104,1783943,True,4,43,0,,1,MNM3
107,1427466,True,12,37,0,,1,MNM3
108,1752088,True,6,37,0,,1,MNM3
116,1247224,True,14,79,0,,1,mnS3
118,1462198,True,14,36,0,,1,MNM3
122,1396639,True,15,36,0,,1,MNM3
123,1169967,True,14,76,0,,1,mnS3
132,1444447,True,16,39,0,,1,MNM3
135,1073548,True,14,36,0,,1,MNM3
144,1416322,True,19,37,0,,1,MNM3
156,1752129,True,14,30,0,,1,MNM3
174,1413955,True,22,31,0,,1,MNM3
178,1330097,True,21,33,0,,1,MNM3
182,1590455,True,5,6,0,,1,MNM4
208,746723,True,5,8,0,,1,MNM1a
209,1123059,True,19,29,0,,1,MNM3
210,1133210,True,21,29,0,,1,MNM3
211,1300637,True,21,28,0,,1,MNM3
212,1190390,True,18,29,0,,1,MNM3
213,1420832,True,21,31,0,,1,MNM3
220,1246922,True,19,29,0,,1,MNM3
222,1740122,True,6,29,0,,1,MNM3
230,1804167,True,12,37,0,,1,MNM3
249,1741937,True,12,30,0,,1,MNM3
253,25956,True,7,4,0,,1,mnS3
256,1658807,True,5,17,0,,1,MNM3
284,1796621,True,17,28,0,,1,MNM3
289,128944,True,4,8,0,,1,mnS3
291,1175823,True,21,24,0,,1,MNM3
296,86926,True,17,23,0,,1,mnS3
298,1702508,True,10,28,0,,1,MNM3
301,1750864,True,20,27,0,,1,MNM3
313,1556223,True,6,10,0,,1,MNM3
316,1558242,True,12,13,0,,1,MNM3
323,1616282,True,5,13,0,,1,MNM3
325,1292884,True,30,25,0,,1,MNM3
368,1178986,True,25,23,0,,1,MNM3
369,1329297,True,13,17,0,,1,MNM3
370,1237406,True,26,20,0,,1,MNM3
371,1369139,True,28,23,0,,1,MNM3
373,1414769,True,26,24,0,,1,MNM3
388,1589707,True,5,18,0,,1,MNM3
390,1522660,True,9,15,0,,1,MNM3
391,1428241,True,4,8,0,,1,MNM2
394,1124270,True,27,56,0,,1,mnS3
395,1357484,True,29,21,0,,1,MNM3
397,1698566,True,18,28,0,,1,MNM3
398,1758224,True,24,24,0,,1,MNM3
400,132996,True,20,26,0,,1,mnS3
402,1719442,True,14,25,0,,1,MNM3
403,1759556,True,22,23,0,,1,MNM3
406,1585668,True,7,12,0,,1,MNM3
837,1344305,True,5,4,0,,1,MNM2
839,1061131,True,31,47,0,,1,mnS3
891,1251516,True,33,51,0,,1,mnS3
897,1095085,True,30,15,0,,1,MNM3
898,1621555,True,8,10,0,,1,MNM3
902,1669034,True,7,14,0,,1,MNM3
903,1670820,True,5,16,0,,1,MNM3
913,1339348,True,41,17,0,,1,MNM3
935,1483963,True,6,13,0,,1,MNM3
951,136674,True,22,20,0,,1,mnS3
979,1549911,True,6,10,0,,1,MNM3
1016,1784320,True,39,15,0,,1,MNM3
1024,1798274,True,37,10,0,,1,MNM6
1033,1625491,True,16,8,0,,1,MNM3
1034,1537647,True,13,8,0,,1,MNM2
1037,1566126,True,9,8,0,,1,MNM3
1040,1517547,True,13,9,0,,1,MNM3
1045,1606050,True,15,10,0,,1,MNM3
1055,30443,True,14,10,0,,1,mnS3
1063,1529091,True,11,11,0,,1,MNM3
1074,1322988,True,43,7,0,,1,MNM2
1082,1737336,True,8,5,0,,1,MNM3
1099,1609884,True,13,11,0,,1,MNM3
1105,1562885,True,10,8,0,,1,MNM3
1106,1539736,True,12,7,0,,1,MNM3
1111,1311512,True,46,5,0,,1,MNM2
1149,1762526,True,21,4,0,,1,MNM3
1150,1583143,True,14,7,0,,1,MNM3
1152,1620855,True,16,5,0,,1,MNM3
1154,1532057,True,17,4,0,,1,MNM3
1163,1536406,True,11,4,0,,1,MNM3
1166,1670702,True,14,4,0,,1,MNM3
1170,463545,True,40,15,0,,1,mnS3
1246,107777,True,25,12,0,,1,mnS3
1285,112685,True,40,4,0,,1,mnS3
60,1132034,True,14,79,1,mnS1,0,
1051,729324,True,11,5,1,MNM1a,0,
1241,1790907,True,39,6,1,MNM3,0,
1312,1818009,True,46,4,1,MNM3,0,
14,1872434,True,4,75,0,,0,

In [ ]:
num_good_recomb_total = np.sum(recomb_df.net_min_supporting_loci_lft_rgt_ge_4)
num_good_recomb_with_mns = np.sum(
    np.logical_and(
        recomb_df.net_min_supporting_loci_lft_rgt_ge_4,
        np.logical_or(recomb_df.num_mns_left > 0, recomb_df.num_mns_right > 0)
    )
)
perc_good_recomb_with_mns = num_good_recomb_with_mns / num_good_recomb_total

num_bad_recomb_total = np.sum(~recomb_df.net_min_supporting_loci_lft_rgt_ge_4)
num_bad_recomb_with_mns = np.sum(
    np.logical_and(
        ~recomb_df.net_min_supporting_loci_lft_rgt_ge_4,
        np.logical_or(recomb_df.num_mns_left > 0, recomb_df.num_mns_right > 0)
    )
)
perc_bad_recomb_with_mns = num_bad_recomb_with_mns / num_bad_recomb_total

print(f"Good recomb. with MNS: {num_good_recomb_with_mns} / {num_good_recomb_total} ({perc_good_recomb_with_mns}%)")
print(f" Bad recomb. with MNS: {num_bad_recomb_with_mns} / {num_bad_recomb_total} ({perc_bad_recomb_with_mns}%)")

Good recomb. with MNS: 115 / 647 (0.1777434312210201%)
 Bad recomb. with MNS: 87 / 672 (0.12946428571428573%)

In [ ]:
# Bad recombinants
pd.set_option("display.max_rows", 1000)
recomb_df[~recomb_df['net_min_supporting_loci_lft_rgt_ge_4']][
    [
        'recombinant',
        'net_min_supporting_loci_lft_rgt_ge_4',
        'net_min_supporting_loci_lft',
        'net_min_supporting_loci_rgt',
        'num_mns_left',
        'mns_left',
        'num_mns_right',
        'mns_right',
    ]
].sort_values(
    by=[
        'num_mns_left',
        'num_mns_right',
    ],
    ascending=False
).head(88)

,recombinant,net_min_supporting_loci_lft_rgt_ge_4,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,num_mns_left,mns_left,num_mns_right,mns_right
591,603964,False,5,1,2,"MNM1,MNM1a",0,
767,708342,False,5,0,2,"MNM1,MNM1a",0,
1289,1790973,False,103,2,2,"MNM3,mnS3",0,
1202,1190249,False,7,1,1,MNM12,2,"MNM7,MNM7a"
1203,1257863,False,51,1,1,MNM3,2,"MNM7,MNM7a"
1211,979454,False,9,2,1,MNM12,2,"MNM7,MNM7a"
0,1438470,False,2,55,1,mnS1,1,MNM3
1237,259308,False,13,2,1,mnS2,1,MNM7a
2,752955,False,2,19,1,mnS1,0,
7,1002412,False,2,38,1,mnS1,0,
10,497286,False,2,37,1,mnS1,0,
11,1210438,False,2,12,1,mnS1,0,
16,1012502,False,2,22,1,mnS1,0,
88,1787791,False,0,31,1,MNM12,0,
142,374005,False,3,9,1,mnS1,0,
495,704507,False,6,0,1,MNM12,0,
501,650489,False,6,1,1,MNM1a,0,
552,462441,False,2,2,1,mnS1,0,
558,515368,False,2,-1,1,MNM11,0,
641,764303,False,6,-1,1,MNM1a,0,
648,944728,False,6,1,1,mnS1,0,
806,1443769,False,8,2,1,MNM1a,0,
1317,1179983,False,62,1,1,mnS3,0,
1318,1771516,False,48,1,1,MNM3,0,
1068,328088,False,5,3,0,,2,"MNM7,MNM7a"
1119,399636,False,24,3,0,,2,"MNM2,mnS3"
1128,828928,False,15,3,0,,2,"MNM7,MNM7a"
1204,1767510,False,25,1,0,,2,"MNM7,MNM7a"
1205,1303819,False,6,2,0,,2,"MNM7,MNM7a"
1206,1383291,False,8,2,0,,2,"MNM7,MNM7a"
1207,274195,False,7,1,0,,2,"MNM7,MNM7a"
1208,49406,False,6,1,0,,2,"MNM7,MNM7a"
1209,1091508,False,9,2,0,,2,"MNM7,MNM7a"
1210,398193,False,7,2,0,,2,"MNM7,MNM7a"
1212,1005926,False,15,2,0,,2,"MNM7,MNM7a"
1213,1028807,False,12,2,0,,2,"MNM7,MNM7a"
1214,757786,False,9,2,0,,2,"MNM7,MNM7a"
1215,838162,False,11,2,0,,2,"MNM7,MNM7a"
1216,1005525,False,6,2,0,,2,"MNM7,MNM7a"
1217,835721,False,7,2,0,,2,"MNM7,MNM7a"
1218,449105,False,7,2,0,,2,"MNM7,MNM7a"
1219,474894,False,7,2,0,,2,"MNM7,MNM7a"
1220,936985,False,9,2,0,,2,"MNM7,MNM7a"
1221,929417,False,12,2,0,,2,"MNM7,MNM7a"
1222,361106,False,9,2,0,,2,"MNM7,MNM7a"
1223,855276,False,11,2,0,,2,"MNM7,MNM7a"
1224,901125,False,8,2,0,,2,"MNM7,MNM7a"
1225,494794,False,15,2,0,,2,"MNM7,MNM7a"
1226,939147,False,10,2,0,,2,"MNM7,MNM7a"
1227,938163,False,9,2,0,,2,"MNM7,MNM7a"
1228,535776,False,9,2,0,,2,"MNM7,MNM7a"
1229,667880,False,9,2,0,,2,"MNM7,MNM7a"
1230,677327,False,15,2,0,,2,"MNM7,MNM7a"
1231,663938,False,13,2,0,,2,"MNM7,MNM7a"
1232,643799,False,13,2,0,,2,"MNM7,MNM7a"
1,1540083,False,1,12,0,,1,MNM3
3,1639578,False,0,12,0,,1,MNM3
4,1798212,False,1,43,0,,1,MNM3
5,1628560,False,0,14,0,,1,MNM3
8,144266,False,3,21,0,,1,mnS3
46,1617903,False,1,16,0,,1,MNM3
318,1679227,False,8,3,0,,1,MNM8
812,1283721,False,8,3,0,,1,MNM9
833,1373820,False,8,3,0,,1,MNM4
980,1328694,False,6,3,0,,1,MNM3
992,1209421,False,3,3,0,,1,MNM2
1090,1140792,False,7,2,0,,1,MNM4
1091,787257,False,8,3,0,,1,MNM4
1092,1522558,False,4,2,0,,1,MNM4
1093,594269,False,10,2,0,,1,MNM4
1094,751633,False,14,2,0,,1,MNM4
1113,1374550,False,9,2,0,,1,MNM3
1147,1422832,False,2,4,0,,1,MNM2
1159,1705459,False,15,3,0,,1,MNM3
1160,1152381,False,12,1,0,,1,MNM3
1161,1072961,False,8,1,0,,1,MNM3
1164,618522,False,7,2,0,,1,MNM3
1168,1482330,False,11,3,0,,1,MNM3
1169,1311517,False,13,2,0,,1,MNM7a
1233,1236577,False,13,2,0,,1,MNM7a
1234,1277567,False,55,0,0,,1,MNM7a
1235,1300077,False,4,2,0,,1,MNM7a
1236,1192036,False,5,2,0,,1,MNM7a
1238,217046,False,10,1,0,,1,MNM7a
1239,1423597,False,11,1,0,,1,MNM7a
1240,1400699,False,6,1,0,,1,MNM7a
1267,1263449,False,11,2,0,,1,MNM2
6,1502609,False,1,8,0,,0,