# Analysing the sc2ts ARG using tskit, numpy and pandas

This notebooks shows examples of analysing the 3.13 million sample sc2ts ARG using the [tskit Python API](https://tskit.dev/tskit/docs/), in conjuction with Pandas and with an emphasis on using vectorised approaches with Numpy. This is to showcase the ease and efficiency with which pandemic scale analyses can be done directly within a notebook environment using only Python, and to provide a starting point for further analyses. We focus on the core computational tasks one might like to perform on a pandemic scale ARG, with the minimal set of external dependencies required to do this.

Please see the tskit [documentation](https://tskit.dev/tskit/docs/stable/) for detailed information on the Python APIs, and the  [tskit tutorials](https://tskit.dev/tutorials/intro.html) site for an introduction to tskit and help with various tasks such as visualisation. Please see the [preprint](https://www.biorxiv.org/content/10.1101/2023.06.08.544212) for background and further details on all aspects of sc2ts and the ARG.

In [1]:
import tszip
import sc2ts
import numpy as np

First, we load the ARG into memory from the compressed representation using [tszip](https://tskit.dev/software/tszip.html), which typically takes less than a second. The object we get back is a [tskit TreeSequence](https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TreeSequence), which we call ``ts`` by convention.

In [2]:
ts = tszip.load("../data/sc2ts_viridian_v2.3.trees.tsz")

When viewed in a notebook environment, the TreeSequence gives some summary information about its contents:

In [3]:
ts

## Information on nodes

The [sc2ts Python API](https://tskit.dev/sc2ts/docs/stable/api.html) provides a few utility functions that take advantage of specific structure of the sc2ts ARG and its metadata. The ``node_data`` function returns a Pandas Dataframe summarising the nodes in the ARG, and in particular, makes the key ``sample_id``, ``pango`` and ``scorpio`` metadata fields efficiently accessible.

In [4]:
dfn = sc2ts.node_data(ts)
dfn

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date
0,B,Vestigial_ignore,.,0,False,False,0,2019-11-18
1,B,Wuhan/Hu-1/2019,.,1,False,False,0,2019-12-26
2,A,SRR11772659,.,2,True,False,1,2020-01-19
3,B,SRR11397727,.,3,True,False,0,2020-01-24
4,B,SRR11397730,.,4,True,False,0,2020-01-24
...,...,...,...,...,...,...,...,...
3423598,AY.4.2,,Delta (AY.4.2-like),3423598,False,False,2,2021-08-28
3423599,HV.1.1,,Omicron (XBB.1-like),3423599,False,False,3,2023-09-08
3423600,BQ.1.1.29,,Omicron (BA.5-like),3423600,False,False,9,2022-10-01
3423601,AY.75,,Delta (B.1.617.2-like),3423601,False,False,9,2021-05-11
3423602,XBB.1.5,,Omicron (XBB-like),3423602,False,False,1,2023-01-02

Pandas provides many powerful functions. For example, here is a breakdown of the numbers of nodes by their Scorpio assignment:

In [5]:
dfn["scorpio"].value_counts()

scorpio
Delta (B.1.617.2-like)           710516
Delta (AY.4-like)                610517
Omicron (BA.2-like)              510017
Omicron (BA.1-like)              462279
Alpha (B.1.1.7-like)             334938
Omicron (BA.5-like)              276859
.                                204075
Delta (AY.4.2-like)              100680
Omicron (XBB.1.5-like)            64953
Omicron (XBB.1-like)              44543
Omicron (BA.4-like)               33800
Omicron (XBB.1.16-like)           15227
Iota (B.1.526-like)               11802
Epsilon (B.1.429-like)             9167
Omicron (XBB-like)                 8752
Gamma (P.1-like)                   6966
Epsilon (B.1.427-like)             4842
Beta (B.1.351-like)                4127
Mu (B.1.621-like)                  1592
Omicron (XE-like)                  1311
Delta (B.1.617.2-like) +K417N      1298
B.1.1.318-like                     1211
Eta (B.1.525-like)                 1010
B.1.617.1-like                      617
Probable Omicron (Unassigned)       562
B.1.1.7-like+E484K                  547
Omicron (Unassigned)                474
Zeta (P.2-like)                     432
A.23.1-like                         206
AV.1-like                           152
Omicron (BA.3-like)                  56
A.23.1-like+E484K                    50
B.1.617.3-like                       25
Name: count, dtype: Int64

We can then use this to identify specific nodes. Suppose we wanted to find the first Alpha node. To do this, we simply need to find oldest node with the corresponding Pango label.

**NOTE** The dataframe returned by ``node_data`` has a ``date`` field, which gives the estimated date for each node, which has day-precision. In order to find the oldest node reliably we need finer precision, which is provided by the ``time`` column in the tskit 
[node table](https://tskit.dev/tskit/docs/stable/data-model.html#node-table). To access this information in Pandas, we add this field to the dataframe. Then, we sort the rows by time and then extract the first record for each Pango designation:

In [6]:
dfn["time"] = ts.nodes_time
dfn_pango = dfn.sort_values("time", ascending=False).groupby(["pango"]).first()
dfn_pango

,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
pango,,,,,,,,
A,,.,9,False,False,1,2019-12-26,1624.0
A.1,,.,273,False,False,2,2020-01-19,1600.0
A.11,SRR23586010,.,4097,True,False,3,2020-03-28,1531.0
A.2,,.,639,False,False,4,2020-02-01,1587.0
A.2.2,ERR12537611,.,1269,True,False,1,2020-03-19,1540.0
...,...,...,...,...,...,...,...,...
XW,ERR9444530,Omicron (BA.2-like),1375044,True,False,1,2022-03-20,809.0
XY,,Omicron (Unassigned),1413970,False,True,2,2022-03-15,814.0
XZ,,Omicron (BA.2-like),1380301,False,False,1,2022-03-09,820.0
Y.1,,.,60919,False,False,1,2020-08-18,1388.0
Z.1,ERR4664951,.,34064,True,False,3,2020-09-15,1360.0

We can then extract the "alpha origin" node easily:

In [7]:
alpha_origin = dfn_pango.loc["B.1.1.7"]
alpha_origin

sample_id
scorpio           Alpha (B.1.1.7-like)
node_id                          94150
is_sample                        False
is_recombinant                   False
num_mutations                       36
date               2020-09-16 00:00:00
time                        1359.91339
Name: B.1.1.7, dtype: object

## Information on mutations

The sc2ts Python API also provides a way to extract information about mutations.

In [8]:
dfm = sc2ts.mutation_data(ts).set_index("node")
dfm

,mutation_id,site_id,position,parent,inherited_state,derived_state,date
node,,,,,,,
9119,0,0,56,-1,G,T,2020-03-22
664794,1,0,56,-1,G,T,2021-07-18
483157,2,0,56,-1,G,T,2021-07-31
551530,3,0,56,-1,G,T,2021-09-01
801925,4,0,56,-1,G,T,2021-09-07
...,...,...,...,...,...,...,...
1847724,2756050,29639,29803,-1,C,T,2023-09-13
1865671,2756051,29639,29803,-1,C,T,2023-10-30
1872586,2756052,29639,29803,-1,C,T,2023-11-17
1866461,2756053,29639,29803,-1,C,A,2023-11-17
1887971,2756054,29639,29803,-1,C,A,2024-01-15

This dataframe has information about each mutation, including the genome position (``position``) and node over which the mutation occured. Here, we're interested in finding all the mutations immediately ancestral to the Alpha origin node found above, and so we add an index on the ``node`` field. Then, getting the mutations is quick and easy:

In [9]:
alpha_origin_mutations = dfm.loc[alpha_origin["node_id"]]
alpha_origin_mutations

,mutation_id,site_id,position,parent,inherited_state,derived_state,date
node,,,,,,,
94150,202963,854,913,-1,C,T,2020-05-23
94150,600152,5315,5388,-1,C,A,2020-05-23
94150,644733,5910,5986,-1,C,T,2020-05-23
94150,731840,6874,6954,-1,T,C,2020-05-23
94150,1033741,11192,11288,-1,T,-,2020-05-23
94150,1033793,11193,11289,-1,C,-,2020-05-23
94150,1033931,11194,11290,-1,T,-,2020-05-23
94150,1034023,11195,11291,-1,G,-,2020-05-23
94150,1034116,11196,11292,-1,G,-,2020-05-23
94150,1034275,11197,11293,-1,T,-,2020-05-23
94150,1034410,11198,11294,-1,T,-,2020-05-23
94150,1034542,11199,11295,-1,T,-,2020-05-23
94150,1034651,11200,11296,-1,T,-,2020-05-23
94150,1259650,14568,14676,-1,C,T,2020-05-23
94150,1294753,15169,15279,-1,C,T,2020-05-23
94150,1346552,16063,16176,-1,T,C,2020-05-23
94150,1741944,21631,21765,-1,T,-,2020-05-23
94150,1744724,21632,21766,-1,A,-,2020-05-23
94150,1747376,21633,21767,-1,C,-,2020-05-23
94150,1748704,21634,21768,-1,A,-,2020-05-23
94150,1749724,21635,21769,-1,T,-,2020-05-23
94150,1750824,21636,21770,-1,G,-,2020-05-23
94150,1794615,21856,21991,-1,T,-,2020-05-23
94150,1798710,21857,21992,-1,T,-,2020-05-23
94150,1802830,21858,21993,-1,A,-,2020-05-23
94150,1928492,22922,23063,-1,A,T,2020-05-23
94150,1942802,23130,23271,-1,C,A,2020-05-23
94150,1971832,23463,23604,-1,C,A,2020-05-23
94150,1985607,23568,23709,-1,C,T,2020-05-23
94150,2047738,24362,24506,-1,T,G,2020-05-23
94150,2073113,24769,24914,-1,G,C,2020-05-23
94150,2455049,27817,27972,-1,C,T,2020-05-23
94150,2467408,27893,28048,-1,G,T,2020-05-23
94150,2482543,27956,28111,-1,A,G,2020-05-23
94150,2506704,28115,28271,-1,A,-,2020-05-23
94150,2609321,28821,28977,-1,C,T,2020-05-23

Here we can see there's quite a lot of mutations, but many of them have the derived state of the gap character ("-"). These represent the approximation of deletions in sc2ts, in which deletions at each site are modelled indepenently. 

We can extract the actual deletion events from this representation by looking at runs of mutations to the gap character and extracting their start and length. We do this using some pandas group-by logic.

In [10]:
dels = alpha_origin_mutations[alpha_origin_mutations["derived_state"] == "-"].copy()
dels["run"] = (dels["position"].diff(1) != 1).cumsum()
dels

,mutation_id,site_id,position,parent,inherited_state,derived_state,date,run
node,,,,,,,,
94150,1033741,11192,11288,-1,T,-,2020-05-23,1
94150,1033793,11193,11289,-1,C,-,2020-05-23,1
94150,1033931,11194,11290,-1,T,-,2020-05-23,1
94150,1034023,11195,11291,-1,G,-,2020-05-23,1
94150,1034116,11196,11292,-1,G,-,2020-05-23,1
94150,1034275,11197,11293,-1,T,-,2020-05-23,1
94150,1034410,11198,11294,-1,T,-,2020-05-23,1
94150,1034542,11199,11295,-1,T,-,2020-05-23,1
94150,1034651,11200,11296,-1,T,-,2020-05-23,1
94150,1741944,21631,21765,-1,T,-,2020-05-23,2
94150,1744724,21632,21766,-1,A,-,2020-05-23,2
94150,1747376,21633,21767,-1,C,-,2020-05-23,2
94150,1748704,21634,21768,-1,A,-,2020-05-23,2
94150,1749724,21635,21769,-1,T,-,2020-05-23,2
94150,1750824,21636,21770,-1,G,-,2020-05-23,2
94150,1794615,21856,21991,-1,T,-,2020-05-23,3
94150,1798710,21857,21992,-1,T,-,2020-05-23,3
94150,1802830,21858,21993,-1,A,-,2020-05-23,3
94150,2506704,28115,28271,-1,A,-,2020-05-23,4

In [11]:
dels_grp = dels.groupby("run")
summary = dels_grp.first() 
summary["length"] = dels_grp.last()["position"] - summary["position"] + 1
summary[["position", "length"]]

     position  length
run
1       11288       9
2       21765       6
3       21991       3
4       28271       1

So, we have 4 deletions: a 9 bp deletion starting at position 11288, 6bp at 21765, etc.

Non deletions are more straightforward to analyse, but it's important to factor out the deletions first because of their multibase nature. This is easily done:

In [12]:
non_dels = alpha_origin_mutations[alpha_origin_mutations["derived_state"] != "-"]
non_dels

,mutation_id,site_id,position,parent,inherited_state,derived_state,date
node,,,,,,,
94150,202963,854,913,-1,C,T,2020-05-23
94150,600152,5315,5388,-1,C,A,2020-05-23
94150,644733,5910,5986,-1,C,T,2020-05-23
94150,731840,6874,6954,-1,T,C,2020-05-23
94150,1259650,14568,14676,-1,C,T,2020-05-23
94150,1294753,15169,15279,-1,C,T,2020-05-23
94150,1346552,16063,16176,-1,T,C,2020-05-23
94150,1928492,22922,23063,-1,A,T,2020-05-23
94150,1942802,23130,23271,-1,C,A,2020-05-23
94150,1971832,23463,23604,-1,C,A,2020-05-23
94150,1985607,23568,23709,-1,C,T,2020-05-23
94150,2047738,24362,24506,-1,T,G,2020-05-23
94150,2073113,24769,24914,-1,G,C,2020-05-23
94150,2455049,27817,27972,-1,C,T,2020-05-23
94150,2467408,27893,28048,-1,G,T,2020-05-23
94150,2482543,27956,28111,-1,A,G,2020-05-23
94150,2609321,28821,28977,-1,C,T,2020-05-23

## Recombination nodes and local trees

The ``node_data`` dataframe has a field ``is_recombinant`` which makes finding the recombination nodes in the sc2ts ARG easy

In [13]:
df_recomb = dfn[dfn.is_recombinant]
df_recomb

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
1894,B.1.157,,.,1894,False,True,2,2020-03-18,1541.000000
25956,B.1.1,,.,25956,False,True,2,2020-07-05,1432.216310
30443,B.1.160,,.,30443,False,True,1,2020-07-02,1435.381418
31804,B.1.426,,.,31804,False,True,0,2020-08-28,1378.000000
36153,B.1.221,,.,36153,False,True,0,2020-06-24,1443.761024
...,...,...,...,...,...,...,...,...,...
1890412,JN.1,,Omicron (BA.2-like),1890412,False,True,3,2024-03-31,67.580387
1890753,JN.1.4.3,,Omicron (BA.2-like),1890753,False,True,2,2024-04-06,61.264855
1891360,XDV.1,,Omicron (BA.2-like),1891360,False,True,8,2023-11-25,194.378857
1891578,JN.1.7.5,,Omicron (BA.2-like),1891578,False,True,2,2024-05-06,31.263776
1892451,XDY,,Omicron (BA.2-like),1892451,False,True,2,2024-04-18,49.903495

XBB is an important recombinant and is well captured by the sc2ts ARG. Its "origin node" is a recombination node, meaning that it has more than one parent in the ARG. We can see that the ``is_recombinant`` flag is True:

In [14]:
xbb_origin = dfn_pango.loc["XBB"]
xbb_origin

sample_id
scorpio            Omicron (XBB-like)
node_id                       1673452
is_sample                       False
is_recombinant                   True
num_mutations                      15
date              2022-05-20 00:00:00
time                       748.159479
Name: XBB, dtype: object

To find where the breakpoint is (almost all recombinants in the current sc2ts ARG have only 2 parents and consequently one breakpoint), we must inspect the tskit [edge table](https://tskit.dev/tskit/docs/stable/data-model.html#edge-table). This simply records the IDs of the parent and child nodes and the interval over which this relationship applies. We then find the edges which record the parents of the XBB origin by looking for those edges in which it is a child:

In [15]:
xbb_edges = np.where(ts.edges_child == xbb_origin["node_id"])[0]
xbb_edges

array([531220, 691647])

We get two edge IDs, which we can then use to get the properties of the edges themselves. One quick way to visualise the information is to access the edge table directly:

In [16]:
ts.tables.edges[xbb_edges]

We can also look at the parents of the event directly:

In [17]:
dfn.loc[ts.edges_parent[xbb_edges]]

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
1628335,BM.1.1.1,,Omicron (BA.2-like),1628335,False,False,1,2022-04-12,786.612065
1303550,BA.2.10,ERR9201084,Omicron (BA.2-like),1303550,True,False,1,2022-02-26,831.000000

To get the breakpoint, we can then take the maximum of the left coordinate:

(Note, we're using two different conventions for accessing the underlying table data here --- they are essentially equivalent and can be mixed and matched as is most convenient.)

In [18]:
bp = np.max(ts.edges_left[xbb_edges])
bp

np.float64(22577.0)

The *effect* of this recombination event is to change the tree to the left and right of the breakpoint. Tskit provides an efficient view over the "local trees" along the genome that result from recombination events. In this case, we would like to examine the trees to the right and left of the breakpoint for XBB. The simplest (and most efficient) way to do this is to first look at the right-hand tree using the ``ts.at`` method.

In [19]:
tree = ts.at(bp)
tree

The tree returned here is an instance of the tskit [Tree](https://tskit.dev/tskit/docs/stable/python-api.html#tskit.Tree) class which provides many operations. This is built around the efficient numerical representation of trees, and specifically, the 
[quintuply linked tree](https://tskit.dev/tskit/docs/stable/data-model.html#quintuply-linked-trees) data structure, in which the tree topology is encoded using a set of numpy arrays. For example, the parent of each node in the tree is represented using the ``parent_array``:

In [20]:
tree.parent_array

array([     -1,      -1,       9, ..., 3421361, 1794512,      -1],
      shape=(3423604,), dtype=int32)

So, ``tree.parent_array[u]`` means "what is the node ID of the parent of node ``u`` in this tree". The ``-1`` values here indicate that a particular node has no parent, and so is either a root or is not "present" in the current tree. We can then verify that the local tree has the correct parent for the right-hand side of the XBB recombination event:

In [21]:
tree.parent_array[xbb_origin["node_id"]]

np.int32(1628335)

We can use the same approach to access the tree on the left hand side of the breakpoint, but it is more efficient to "mutate" the current tree instance using the ``prev()`` method. This is because ``ts.at()`` requires us to create a new tree instance and to apply all the edges that intersect with the given point. Using the ``prev`` method, on the other hand, takes advantage of the fact that there's very little difference between the trees at either side of the breakpoint and makes those minimal changes.

In [22]:
tree.prev()
tree

Now we can also verify that the left-hand parent of the XBB recombination node is what we extracted from the node table above.

In [23]:
tree.parent_array[xbb_origin["node_id"]]

np.int32(1303550)

## Getting the ancestors of a node in a tree

An operation that we're often interested in is to get the ancestors of a node in a particular tree. Using the ``ancestors`` methods along with Pandas selection provides an easy way to access data on the ancestors of the Alpha origin node.

In [24]:
tree = ts.first()   
u = alpha_origin["node_id"]
dfn.iloc[[u] + list(tree.ancestors(u))]

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
94150,B.1.1.7,,Alpha (B.1.1.7-like),94150,False,False,36,2020-09-16,1359.913390
5396,B.1.1,,.,5396,False,False,3,2020-01-28,1591.008475
118,B.1.1,,.,118,False,False,3,2020-01-28,1591.012119
68,B.1,,.,68,False,False,1,2020-01-28,1591.684194
12,B.1,SRR11597205,.,12,True,False,2,2020-01-28,1591.684194
33,B,,.,33,False,False,1,2019-12-26,1624.000000
1,B,Wuhan/Hu-1/2019,.,1,False,False,0,2019-12-26,1624.000000

**Note:** In this example we use the first tree in the sequence to access the ancestors of the Alpha origin node. This is valid here because there is no recombinant among those ancestors. When recombination is present among the ancestors, more care is required.

## Iterating over all trees

A common pattern in analysing ARGs with tskit is to iterate sequentially over all local trees along the genome. This is done using the ``.trees()`` iterator, which again takes advantage of the fact that adjacent trees are very similar for efficiency. Here we use this to count the number of polytomies (nodes with > 2 children) in each local tree. This is done using Numpy functions on the ``num_children_array``, which is a zero-copy view on a per-node count maintained by the underlying C library.

In [25]:
%%time
num_polytomies = np.zeros(ts.num_trees, dtype=int)
for tree in ts.trees():
    num_polytomies[tree.index] = np.sum(tree.num_children_array > 2)
np.min(num_polytomies), np.max(num_polytomies)

CPU times: user 531 ms, sys: 80.8 ms, total: 612 ms
Wall time: 682 ms

(np.int64(272356), np.int64(272391))

## Examining children

The numpy ``argmax`` function gives us a conveient way to find the ID of the node which has the largest number of children:

In [26]:
tree = ts.first()
u = np.argmax(tree.num_children_array)
tree.num_children_array[u]

np.int32(13877)

This has an impressive 13,877 children! We can first look at its path back to root, and verify that it is valid across all trees by checking that there are no recombinants in its ancestry:

In [27]:
dfn.loc[[u] + list(tree.ancestors(u))]

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
965911,BA.2.5,,Omicron (BA.2-like),965911,False,False,1,2021-10-19,961.932564
871741,BA.2,,Omicron (BA.2-like),871741,False,False,1,2021-10-19,961.932564
1171677,BA.2,,Omicron (BA.2-like),1171677,False,False,43,2021-10-19,961.932564
871742,BA.2,,Omicron (BA.3-like),871742,False,False,16,2021-03-22,1172.200788
871743,B.1.1.529,,Omicron (Unassigned),871743,False,False,64,2020-10-11,1334.549092
871744,B.1.1,,.,871744,False,False,1,2020-01-28,1591.009237
5904,B.1.1,,.,5904,False,False,1,2020-01-28,1591.009237
118,B.1.1,,.,118,False,False,3,2020-01-28,1591.012119
68,B.1,,.,68,False,False,1,2020-01-28,1591.684194
12,B.1,SRR11597205,.,12,True,False,2,2020-01-28,1591.684194
33,B,,.,33,False,False,1,2019-12-26,1624.000000
1,B,Wuhan/Hu-1/2019,.,1,False,False,0,2019-12-26,1624.000000

We can then get the list of children for that node using the ``tree.children()`` method, and extract the relevant rows from the node data table:

In [28]:
df_children = dfn.loc[list(tree.children(u))]
df_children

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
932322,BA.2,,Omicron (BA.2-like),932322,False,False,1,2021-10-19,961.932564
963511,BA.2,SRR18518948,Omicron (BA.2-like),963511,True,False,1,2021-12-01,918.000000
1040012,BA.2.10,SRR18518942,Omicron (BA.2-like),1040012,True,False,1,2021-12-18,901.000000
1051378,BA.2,SRR17888957,Omicron (BA.2-like),1051378,True,False,1,2021-12-22,897.000000
1051379,BA.2,SRR18518984,Omicron (BA.2-like),1051379,True,False,1,2021-12-22,897.000000
...,...,...,...,...,...,...,...,...,...
3413908,BA.2,,Omicron (BA.2-like),3413908,False,False,1,2022-01-03,885.685142
3417997,BA.2,,Omicron (BA.2-like),3417997,False,False,2,2021-12-21,898.484854
3418929,BA.2,,Omicron (BA.2-like),3418929,False,False,6,2022-02-09,848.720332
3421078,BA.2,,Omicron (BA.2-like),3421078,False,False,4,2021-12-04,915.166649
3421166,BA.2,,Omicron (BA.2-like),3421166,False,False,1,2022-01-19,869.276483

When we break down the counts of those nodes by their sample status and number of mutations, we see that we have over 10,000 samples which are identical to the focal node. Thus, this seems like a well-inferred node capturing a very deeply sampled phase of the BA.2 outbreak.

In [29]:
df_children[["num_mutations", "is_sample"]].value_counts()

num_mutations  is_sample
0              True         10241
1              True          2460
               False          729
2              True           306
3              True            64
2              False           52
4              True            14
3              False            4
5              True             3
4              False            2
6              False            1
9              True             1
Name: count, dtype: int64

## All descendants

Getting the descendants of a node in a particular tree is straightforward, and can be done efficiently in the standard traversal orders. For example, here we get all the nodes descending from the Alpha origin in the first tree in preorder, and extract the corresponding dataframe:

In [30]:
tree = ts.first()
descendants = tree.preorder(alpha_origin["node_id"])
descendants

array([ 94150,  50503,  50472, ..., 300225, 301946,  93884],
      shape=(335498,), dtype=int32)

In [31]:
alpha_descendants = dfn.loc[descendants]
alpha_descendants

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
94150,B.1.1.7,,Alpha (B.1.1.7-like),94150,False,False,36,2020-09-16,1359.913390
50503,B.1.1.7,,Alpha (B.1.1.7-like),50503,False,False,1,2020-09-16,1359.913390
50472,B.1.1.7,ERR4827181,Alpha (B.1.1.7-like),50472,True,False,0,2020-10-21,1324.000000
50473,B.1.1.7,ERR4827009,Alpha (B.1.1.7-like),50473,True,False,1,2020-10-21,1324.000000
56778,B.1.1.7,ERR4862251,Alpha (B.1.1.7-like),56778,True,False,1,2020-11-05,1309.000000
...,...,...,...,...,...,...,...,...,...
3421322,B.1.1.7,,Alpha (B.1.1.7-like),3421322,False,False,1,2021-01-01,1252.089511
218615,B.1.1.7,SRR16617144,Alpha (B.1.1.7-like),218615,True,False,2,2021-03-24,1170.000000
300225,B.1.1.7,ERR5999240,Alpha (B.1.1.7-like),300225,True,False,6,2021-05-24,1109.000000
301946,B.1.1.7,ERR6010769,Alpha (B.1.1.7-like),301946,True,False,1,2021-05-26,1107.000000
93884,B.1.1.7,ERR5178290,Alpha (B.1.1.7-like),93884,True,False,0,2020-12-29,1255.000000

However, this is an approximation to the true descendants of the node, because there are some recombinants descending from it.

In [32]:
alpha_descendants[alpha_descendants["is_recombinant"]]

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
303651,B.1.1.7,,Alpha (B.1.1.7-like),303651,False,True,0,2021-05-12,1121.000000
288240,B.1.526,,Iota (B.1.526-like),288240,False,True,2,2021-04-21,1142.998623
274210,B.1.1.7,,Alpha (B.1.1.7-like),274210,False,True,3,2021-04-11,1152.736595
366716,Q.3,,Alpha (B.1.1.7-like),366716,False,True,1,2021-06-25,1077.134403
185317,B.1.1.7,,Alpha (B.1.1.7-like),185317,False,True,3,2021-03-03,1191.000000
217062,B.1.1.7,,Alpha (B.1.1.7-like),217062,False,True,1,2021-03-15,1179.000000
258084,B.1.1.7,,Alpha (B.1.1.7-like),258084,False,True,1,2021-04-01,1162.561415
316191,B.1.1.7,,Alpha (B.1.1.7-like),316191,False,True,0,2021-04-28,1135.643273
277205,B.1.526,,Iota (B.1.526-like),277205,False,True,1,2021-04-13,1150.284851
259323,B.1.1.7,,Alpha (B.1.1.7-like),259323,False,True,0,2021-03-01,1193.000000
356180,B.1.1.7,,Alpha (B.1.1.7-like),356180,False,True,2,2021-06-15,1087.558282
258068,B.1.1.7,,Alpha (B.1.1.7-like),258068,False,True,2,2021-03-15,1179.796653
250192,B.1.1.7,,Alpha (B.1.1.7-like),250192,False,True,1,2021-03-24,1170.421908
208408,B.1.1.7,,Alpha (B.1.1.7-like),208408,False,True,0,2021-02-25,1197.262467
293039,B.1.1.7,,Alpha (B.1.1.7-like),293039,False,True,0,2021-05-10,1123.000000
114056,B.1.177.9,,.,114056,False,True,3,2021-01-03,1250.069933
115377,B.1.1.7,,.,115377,False,True,0,2020-12-10,1274.000000
166252,B.1.1.7,,Alpha (B.1.1.7-like),166252,False,True,1,2021-02-16,1206.000000

To get the true set of descendants of this node we must currently take the union of the descendants across all trees as follows.

**NOTE:** efficient support for this operation is planned in tskit

In [33]:
all_descendants = []
for tree in ts.trees():
    all_descendants = np.union1d(
        all_descendants, np.sort(tree.preorder(alpha_origin["node_id"])))

In [34]:
alpha_descendants = dfn.loc[all_descendants]
alpha_descendants

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date,time
50472,B.1.1.7,ERR4827181,Alpha (B.1.1.7-like),50472,True,False,0,2020-10-21,1324.000000
50473,B.1.1.7,ERR4827009,Alpha (B.1.1.7-like),50473,True,False,1,2020-10-21,1324.000000
50474,B.1.1.7,ERR4833995,Alpha (B.1.1.7-like),50474,True,False,1,2020-10-21,1324.000000
50475,B.1.1.7,ERR4827287,Alpha (B.1.1.7-like),50475,True,False,1,2020-10-22,1323.000000
50476,B.1.1.7,ERR4848983,Alpha (B.1.1.7-like),50476,True,False,0,2020-10-23,1322.000000
...,...,...,...,...,...,...,...,...,...
3423499,B.1.1.7,,Alpha (B.1.1.7-like),3423499,False,False,1,2021-03-14,1180.000000
3423567,B.1.1.7,,Alpha (B.1.1.7-like),3423567,False,False,1,2021-01-13,1240.054834
3423585,B.1.1.7,,Alpha (B.1.1.7-like),3423585,False,False,2,2021-02-24,1198.000000
3423594,B.1.1.7,,Alpha (B.1.1.7-like),3423594,False,False,2,2020-10-16,1329.904350
3423596,B.1.1.7,,Alpha (B.1.1.7-like),3423596,False,False,2,2021-04-30,1133.431471