In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing', '/gpfs3/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/bin', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/lib-dynload', '/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/src/pangonet/src', '/users/kelleher/sbk774/.cache/snakemake/snakemake/source-cache/snakemake-runtime-cache/tmpaipjd53a/file/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks']);import pickle;snakemake = pickle.loads(b"\x80\x04\x95\xe0\x04\x00\x00\x00\x00\x00\x00\x8c\x16snakemake.iocontainers\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94h\x00\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c?sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_mmps.trees.tsz\x94\x8c'sc2ts_2024-06-06_intersection.trees.tsz\x94\x8c-usher_2024-06-06_intersection_ds_di.trees.tsz\x94\x8c\x18usher_viridian.trees.tsz\x94e}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x12h\x00\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbub\x8c\x06output\x94h\x00\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94(\x8c#sc2ts_viridian_2024-06-06.trees.tsz\x94\x8c)sc2ts_viridian_inter_2024-06-06.trees.tsz\x94\x8c)usher_viridian_inter_2024-06-06.trees.tsz\x94e}\x94(h\x0e}\x94h\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbub\x8c\r_params_store\x94h\x00\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\x0e}\x94h\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x00\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c\n2024-06-06\x94a}\x94(h\x0e}\x94\x8c\x04DATE\x94K\x00N\x86\x94sh\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sb\x8c\x04DATE\x94h:ub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x00\x8c\x0cResourceList\x94\x93\x94)\x81\x94(\x8c\x04/tmp\x94K\x01K\x01e}\x94(h\x0e}\x94(\x8c\x06tmpdir\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06_cores\x94K\x02N\x86\x94uh\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbhMhJhOK\x01hQK\x01ub\x8c\x03log\x94h\x00\x8c\x03Log\x94\x93\x94)\x81\x94\x8c&logs/final_arg_report_2024-06-06.ipynb\x94a}\x94(h\x0e}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbh_h\\ub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\x10final_arg_report\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cY/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks\x94ub.");from snakemake.logging import logger;from snakemake.iocontainers import Snakemake;import os; os.chdir(r'/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing');
######## snakemake preamble end #########

In [2]:
import sc2ts
import tszip
import shutil

In [3]:
# Copy the dated ARGs to their published viridian names. The full usher
# tree (the last input) is date-independent and published separately, so
# it is loaded directly below rather than copied here.
assert len(snakemake.input) == 4 and len(snakemake.output) == 3
for fin, fout in zip(snakemake.input[:3], snakemake.output):
    shutil.copy(fin, fout)

In [4]:
sc2ts_viridian = snakemake.output[0]
sc2ts_viridian_inter = snakemake.output[1]
usher_viridian_inter = snakemake.output[2]
# The usher tree is published separately (undated) and passed as the last input.
usher_viridian = snakemake.input[3]

# Main sc2ts ARG

Built from Viridian data up to 2024-06-06. Internal nodes have been dated using tsdate, and contains deletions and highly homoplasic sites post-hoc mapped on by parsimony.

In [5]:
ts_sc2ts = tszip.load(sc2ts_viridian)
ts_sc2ts

In [6]:
sc2ts.node_data(ts_sc2ts)

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date
0,B,Vestigial_ignore,.,0,False,False,0,2019-11-19
1,B,Wuhan/Hu-1/2019,.,1,False,False,0,2019-12-26
2,A,SRR11772659,.,2,True,False,1,2020-01-19
3,B,SRR11397727,.,3,True,False,0,2020-01-24
4,B,SRR11397730,.,4,True,False,0,2020-01-24
...,...,...,...,...,...,...,...,...
3424141,HV.1.1,,Omicron (XBB.1-like),3424141,False,False,3,2023-09-09
3424142,BQ.1.1.29,,Omicron (BA.5-like),3424142,False,False,9,2022-10-02
3424143,BA.1.1,,Omicron (BA.1-like),3424143,False,False,1,2021-11-02
3424144,AY.75,,Delta (B.1.617.2-like),3424144,False,False,9,2021-05-17
3424145,XBB.1.5,,Omicron (XBB-like),3424145,False,False,1,2023-01-02

In [7]:
sc2ts.mutation_data(ts_sc2ts)

,mutation_id,site_id,position,parent,node,inherited_state,derived_state,date
0,0,0,56,-1,9044,G,T,2020-03-22
1,1,0,56,-1,664838,G,T,2021-07-19
2,2,0,56,-1,479708,G,T,2021-07-31
3,3,0,56,-1,549470,G,T,2021-09-01
4,4,0,56,-1,802956,G,T,2021-09-07
...,...,...,...,...,...,...,...,...
2761029,2761029,29639,29803,-1,1850758,C,T,2023-09-13
2761030,2761030,29639,29803,-1,1868897,C,T,2023-10-30
2761031,2761031,29639,29803,-1,1875756,C,T,2023-11-17
2761032,2761032,29639,29803,-1,1869637,C,A,2023-11-17
2761033,2761033,29639,29803,-1,1891232,C,A,2024-01-16

In [8]:
ts_sc2ts.metadata

{'time_zero_date': '2024-06-06'}

# Main UShER tree 

Translation of the Viridian UShER tree to tskit format. Time units are uncalibrated and branch-lengths are not meaningful.

In [9]:
ts_usher = tszip.load(usher_viridian)
ts_usher

In [10]:
sc2ts.node_data(ts_usher)

,sample_id,node_id,is_sample,is_recombinant,num_mutations,date
0,node_1,0,False,False,0,2024-04-06
1,node_2,1,False,False,1,2024-05-20
2,node_3,2,False,False,1,2024-05-21
3,node_4,3,False,False,2,2024-05-26
4,node_5,4,False,False,1,2024-05-27
...,...,...,...,...,...,...
5345014,ERR4208960,5345014,True,False,0,2024-06-06
5345015,ERR4204653,5345015,True,False,0,2024-06-06
5345016,ERR4206665,5345016,True,False,0,2024-06-06
5345017,ERR4204400,5345017,True,False,0,2024-06-06
5345018,SRR11494564,5345018,True,False,0,2024-06-06

In [11]:
sc2ts.mutation_data(ts_usher)

,mutation_id,site_id,position,parent,node,inherited_state,derived_state,date
0,0,0,73,-1,2413157,A,G,2024-06-02
1,1,0,73,-1,3230755,A,G,2024-06-05
2,2,0,73,-1,3329486,A,G,2024-06-05
3,3,0,73,-1,4170488,A,G,2024-06-05
4,4,0,73,-1,4178891,A,C,2024-06-05
...,...,...,...,...,...,...,...,...
3469024,3469024,27962,29768,-1,5132309,A,G,2024-06-06
3469025,3469025,27962,29768,-1,5198706,A,G,2024-06-06
3469026,3469026,27962,29768,-1,5205949,A,T,2024-06-06
3469027,3469027,27962,29768,-1,5296907,A,G,2024-06-06
3469028,3469028,27962,29768,-1,5329314,A,G,2024-06-06

In [12]:
ts_usher.metadata

{'time_zero_date': '2024-06-06'}

# Intersection sc2ts ARG

Subset of main sc2ts ARG subset to the intersection of samples and sites common to sc2ts and UShER. Internal nodes have **not** been dated by tsdate and so will likely differ from the node dates on the main ARG.

In [13]:
ts_sc2ts_inter = tszip.load(sc2ts_viridian_inter)
ts_sc2ts_inter

In [14]:
sc2ts.node_data(ts_sc2ts_inter)

,sample_id,node_id,is_sample,is_recombinant,num_mutations,date
0,SRR11772659,0,True,False,1,2020-01-19
1,SRR11397727,1,True,False,0,2020-01-24
2,SRR11597198,2,True,False,0,2020-01-25
3,SRR11597221,3,True,False,0,2020-01-25
4,SRR11597143,4,True,False,3,2020-01-28
...,...,...,...,...,...,...
3402829,,3402829,False,False,1,2020-01-07
3402830,,3402830,False,False,1,2020-01-04
3402831,,3402831,False,False,1,2020-01-01
3402832,Wuhan/Hu-1/2019,3402832,False,False,0,2019-12-26
3402833,Vestigial_ignore,3402833,False,False,0,2019-12-25

In [15]:
sc2ts.mutation_data(ts_sc2ts_inter)

,mutation_id,site_id,position,parent,node,inherited_state,derived_state,date
0,0,0,73,-1,389028,A,G,2021-08-12
1,1,0,73,-1,879701,A,G,2021-12-19
2,2,0,73,-1,944619,A,G,2022-01-15
3,3,0,73,-1,999070,A,C,2022-01-28
4,4,0,73,-1,3217437,A,G,2022-02-02
...,...,...,...,...,...,...,...,...
2605860,2605860,27962,29768,-1,1376630,A,G,2022-08-04
2605861,2605861,27962,29768,-1,1417815,A,G,2022-09-14
2605862,2605862,27962,29768,-1,3152335,A,G,2022-11-27
2605863,2605863,27962,29768,-1,1533431,A,G,2023-03-21
2605864,2605864,27962,29768,-1,1558029,A,C,2023-08-09

In [16]:
ts_sc2ts.metadata

{'time_zero_date': '2024-06-06'}

# Intersection UShER ARG

Subset of main UShER ARG subset to the intersection of samples and sites common to both. Internal nodes have been dated by tsdate.

In [17]:
ts_usher_inter =tszip.load(usher_viridian_inter)
ts_usher_inter

In [18]:
sc2ts.node_data(ts_usher_inter)

,Date_tree,sample_id,node_id,is_sample,is_recombinant,num_mutations
0,2020-01-19,SRR11772659,0,True,False,0
1,2020-01-24,SRR11397727,1,True,False,0
2,2020-01-25,SRR11597198,2,True,False,0
3,2020-01-25,SRR11597221,3,True,False,0
4,2020-01-28,SRR11597143,4,True,False,3
...,...,...,...,...,...,...
3754900,,node_1696,3754900,False,False,1
3754901,,node_1695,3754901,False,False,1
3754902,,node_1694,3754902,False,False,1
3754903,,node_1693,3754903,False,False,1
3754904,,node_1,3754904,False,False,0

In [19]:
sc2ts.mutation_data(ts_usher_inter)

,mutation_id,site_id,position,parent,node,inherited_state,derived_state
0,0,0,73,-1,3701085,A,G
1,1,0,73,-1,879701,A,G
2,2,0,73,-1,944619,A,G
3,3,0,73,-1,1163600,A,G
4,4,0,73,-1,3317143,A,G
...,...,...,...,...,...,...,...
2552465,2552465,27962,29768,-1,1376630,A,G
2552466,2552466,27962,29768,-1,3416329,A,G
2552467,2552467,27962,29768,-1,3409941,A,G
2552468,2552468,27962,29768,-1,1533431,A,G
2552469,2552469,27962,29768,-1,1558029,A,C

In [20]:
ts_usher_inter.metadata

{'sc2ts': {'date': '2024-06-06'}}