In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing', '/gpfs3/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/bin', '/apps/eb/el8/2023a/epyc/software/Python/3.11.3-GCCcore-12.3.0/easybuild/python', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/lib-dynload', '/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/src/pangonet/src', '/users/kelleher/sbk774/.cache/snakemake/snakemake/source-cache/snakemake-runtime-cache/tmpcn3b7hlt/file/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks']);import pickle;snakemake = pickle.loads(b"\x80\x04\x95\xc1\x04\x00\x00\x00\x00\x00\x00\x8c\x16snakemake.iocontainers\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94h\x00\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c?sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_mmps.trees.tsz\x94\x8c usher_v1_2024-06-06_mm.trees.tsz\x94\x8c'sc2ts_2024-06-06_intersection.trees.tsz\x94\x8c-usher_2024-06-06_intersection_ds_di.trees.tsz\x94e}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x12h\x00\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbub\x8c\x06output\x94h\x00\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94(\x8c\x1dsc2ts_viridian_v2.0.trees.tsz\x94\x8c\x1dusher_viridian_v1.0.trees.tsz\x94\x8c#sc2ts_viridian_inter_v2.0.trees.tsz\x94\x8c#usher_viridian_inter_v2.0.trees.tsz\x94e}\x94(h\x0e}\x94h\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbub\x8c\r_params_store\x94h\x00\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\x0e}\x94h\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x00\x8c\tWildcards\x94\x93\x94)\x81\x94}\x94(h\x0e}\x94h\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x00\x8c\x0cResourceList\x94\x93\x94)\x81\x94(\x8c\x04/tmp\x94K\x01K\x01e}\x94(h\x0e}\x94(\x8c\x06tmpdir\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06_cores\x94K\x02N\x86\x94uh\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbhJhGhLK\x01hNK\x01ub\x8c\x03log\x94h\x00\x8c\x03Log\x94\x93\x94)\x81\x94\x8c\x1blogs/final_arg_report.ipynb\x94a}\x94(h\x0e}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\x10]\x94(h\x12h\x13eh\x12h\x15)\x81\x94}\x94h\x18h\x12sbh\x13h\x15)\x81\x94}\x94h\x18h\x13sbh\\hYub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\nfinal_args\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cY/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks\x94ub.");from snakemake.logging import logger;from snakemake.iocontainers import Snakemake;import os; os.chdir(r'/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing');
######## snakemake preamble end #########

In [2]:
import sc2ts
import tszip
import shutil

In [3]:
assert len(snakemake.input) == len(snakemake.output) == 4
for fin, fout in zip(snakemake.input, snakemake.output):
    shutil.copy(fin, fout)

In [4]:
sc2ts_viridian = snakemake.output[0]
usher_viridian = snakemake.output[1]
sc2ts_viridian_inter = snakemake.output[2]
usher_viridian_inter = snakemake.output[3]

# Main sc2ts ARG

Built from Viridian data up to 2023-02-21. Internal nodes have been dated using tsdate, and contains deletions and highly homoplasic sites post-hoc mapped on by parsimony.

In [5]:
ts_sc2ts = tszip.load(sc2ts_viridian)
ts_sc2ts

In [6]:
sc2ts.node_data(ts_sc2ts)

,pango,sample_id,scorpio,node_id,is_sample,is_recombinant,num_mutations,date
0,B,Vestigial_ignore,.,0,False,False,0,2019-11-19
1,B,Wuhan/Hu-1/2019,.,1,False,False,0,2019-12-26
2,A,SRR11772659,.,2,True,False,1,2020-01-19
3,B,SRR11397727,.,3,True,False,0,2020-01-24
4,B,SRR11397730,.,4,True,False,0,2020-01-24
...,...,...,...,...,...,...,...,...
3104343,AY.119,,Delta (B.1.617.2-like),3104343,False,False,3,2021-05-17
3104344,AY.9,,Delta (B.1.617.2-like),3104344,False,False,7,2021-04-12
3104345,AY.3,,Delta (B.1.617.2-like),3104345,False,False,1,2021-05-15
3104346,BA.1.1,,Omicron (BA.1-like),3104346,False,False,1,2021-11-05
3104347,AY.75,,Delta (B.1.617.2-like),3104347,False,False,9,2021-05-17

In [7]:
sc2ts.mutation_data(ts_sc2ts)

,mutation_id,site_id,position,parent,node,inherited_state,derived_state,date
0,0,24,25,-1,693423,T,A,2021-09-14
1,1,37,38,-1,14150,A,G,2020-04-21
2,2,42,43,-1,368554,T,A,2021-07-17
3,3,42,43,-1,460861,T,C,2021-07-24
4,4,42,43,-1,724113,T,C,2021-08-21
...,...,...,...,...,...,...,...,...
2533629,2533629,29838,29850,-1,747264,A,G,2021-10-18
2533630,2533630,29838,29850,-1,777583,A,G,2021-10-21
2533631,2533631,29838,29850,-1,1039587,A,G,2021-12-10
2533632,2533632,29838,29850,-1,1244209,A,G,2022-01-12
2533633,2533633,29838,29850,-1,1224444,A,G,2022-01-31

In [8]:
ts_sc2ts.metadata

{'time_zero_date': '2024-06-06'}

# Main UShER tree 

Translation of the Viridian UShER tree to tskit format. Time units are uncalibrated and branch-lengths are not meaningful.

In [9]:
ts_usher = tszip.load(usher_viridian)
ts_usher

In [10]:
sc2ts.node_data(ts_usher)

,sample_id,node_id,is_sample,is_recombinant,num_mutations,date
0,ERR4085584,0,True,False,0,2024-06-06
1,ERR4086315,1,True,False,0,2024-06-06
2,ERR4091746,2,True,False,0,2024-06-06
3,ERR4165155,3,True,False,0,2024-06-06
4,ERR4204267,4,True,False,0,2024-06-06
...,...,...,...,...,...,...
5345014,SRR21886505,5345014,True,False,5,2024-06-06
5345015,node_763111,5345015,False,False,1,2024-06-04
5345016,SRR21635465,5345016,True,False,0,2024-06-06
5345017,node_763112,5345017,False,False,1,2024-06-05
5345018,SRR21795271,5345018,True,False,0,2024-06-06

In [11]:
sc2ts.mutation_data(ts_usher)

,mutation_id,site_id,position,parent,node,inherited_state,derived_state,date
0,0,0,267,-1,1235535,T,A,2024-06-06
1,1,0,267,-1,5297533,T,G,2024-06-06
2,2,1,269,-1,246856,G,A,2024-06-01
3,3,1,269,-1,2677518,G,A,2024-06-01
4,4,1,269,-1,4780608,G,A,2024-06-01
...,...,...,...,...,...,...,...,...
3364836,3364836,27507,29671,-1,4693921,A,T,2024-06-06
3364837,3364837,27507,29671,-1,4741596,A,T,2024-06-06
3364838,3364838,27507,29671,-1,4754269,A,T,2024-06-06
3364839,3364839,27507,29671,-1,4806294,A,G,2024-06-06
3364840,3364840,27507,29671,-1,5084179,A,G,2024-06-06

In [12]:
ts_usher.metadata

{'time_zero_date': '2024-06-06'}

# Intersection sc2ts ARG

Subset of main sc2ts ARG subset to the intersection of samples and sites common to sc2ts and UShER. Internal nodes have **not** been dated by tsdate and so will likely differ from the node dates on the main ARG.

In [13]:
ts_sc2ts_inter = tszip.load(sc2ts_viridian_inter)
ts_sc2ts_inter

In [14]:
sc2ts.node_data(ts_sc2ts_inter)

,sample_id,node_id,is_sample,is_recombinant,num_mutations,date
0,SRR11772659,0,True,False,1,2020-01-19
1,SRR11397727,1,True,False,0,2020-01-24
2,SRR11597198,2,True,False,0,2020-01-25
3,SRR11597221,3,True,False,0,2020-01-25
4,SRR11597143,4,True,False,2,2020-01-28
...,...,...,...,...,...,...
3095322,,3095322,False,False,1,2020-01-07
3095323,,3095323,False,False,1,2020-01-04
3095324,,3095324,False,False,1,2020-01-01
3095325,Wuhan/Hu-1/2019,3095325,False,False,0,2019-12-26
3095326,Vestigial_ignore,3095326,False,False,0,2019-12-25

In [15]:
sc2ts.mutation_data(ts_sc2ts_inter)

,mutation_id,site_id,position,parent,node,inherited_state,derived_state,date
0,0,1,269,-1,5525,G,A,2020-04-08
1,1,1,269,-1,3074076,G,A,2021-01-04
2,2,1,269,-1,77772,G,A,2021-01-04
3,3,1,269,-1,96256,G,A,2021-01-24
4,4,1,269,-1,101271,G,A,2021-01-27
...,...,...,...,...,...,...,...,...
2416516,2416516,27504,29671,-1,1391696,A,G,2023-02-12
2416517,2416517,27504,29671,-1,2831887,A,T,2023-10-13
2416518,2416518,27504,29671,-1,1443072,A,T,2023-10-24
2416519,2416519,27504,29671,-1,1445755,A,T,2023-11-08
2416520,2416520,27504,29671,-1,2830624,A,T,2023-11-17

In [16]:
ts_sc2ts.metadata

{'time_zero_date': '2024-06-06'}

# Intersection UShER ARG

Subset of main UShER ARG subset to the intersection of samples and sites common to both. Internal nodes have been dated by tsdate.

In [17]:
ts_usher_inter =tszip.load(usher_viridian_inter)
ts_usher_inter

In [18]:
sc2ts.node_data(ts_usher_inter)

,Date_tree,sample_id,node_id,is_sample,is_recombinant,num_mutations
0,2020-01-19,SRR11772659,0,True,False,0
1,2020-01-24,SRR11397727,1,True,False,0
2,2020-01-25,SRR11597198,2,True,False,0
3,2020-01-25,SRR11597221,3,True,False,0
4,2020-01-28,SRR11597143,4,True,False,2
...,...,...,...,...,...,...
3405802,,node_1696,3405802,False,False,1
3405803,,node_1695,3405803,False,False,1
3405804,,node_1694,3405804,False,False,0
3405805,,node_1693,3405805,False,False,1
3405806,,node_1,3405806,False,False,0

In [19]:
sc2ts.mutation_data(ts_usher_inter)

,mutation_id,site_id,position,parent,node,inherited_state,derived_state
0,0,1,269,-1,5525,G,A
1,1,1,269,-1,3378998,G,A
2,2,1,269,-1,96256,G,A
3,3,1,269,-1,77772,G,A
4,4,1,269,-1,3369665,G,A
...,...,...,...,...,...,...,...
2273194,2273194,27504,29671,-1,1367287,A,T
2273195,2273195,27504,29671,-1,1445755,A,T
2273196,2273196,27504,29671,-1,3089870,A,T
2273197,2273197,27504,29671,-1,1443072,A,T
2273198,2273198,27504,29671,-1,3080955,A,T

In [20]:
ts_usher_inter.metadata

{'sc2ts': {'date': '2024-06-06'}}